//deleteUI AttrEdshellModNodeFormLayout;
global proc AEshellModNodeTemplate( string $nodeName )
{
	editorTemplate -beginScrollLayout;
	
	editorTemplate -beginLayout "ShellMod 1shape settings" -collapse 0;
	editorTemplate -addControl "offsetZ";
	editorTemplate -addControl "chaserEdgeWeight";
	editorTemplate -addControl "segments";
	editorTemplate -addControl "straightenEdgesAngle";
	editorTemplate -addControl "smoothMeshSubdiv";
	editorTemplate -addSeparator;
	editorTemplate -addControl "chamferEdges";
	editorTemplate -addControl "chamferEdgeFactor";
	editorTemplate -addSeparator;
	editorTemplate -addControl "capTop";
	editorTemplate -addControl "capBottom";
	editorTemplate -addControl "smoothNormals";
	editorTemplate -addControl "reverseNormals";
	editorTemplate -addControl "straightenEdges";
	editorTemplate -addControl "autoSegments";
	
	editorTemplate -addSeparator;
	editorTemplate -addControl "baseMeshDisplayOverride";

	AEaddRampControl( $nodeName + ".profileRamp" );
	editorTemplate -addControl "profileStrength";
	
	editorTemplate -addSeparator;
	editorTemplate -label "Built in Presets" -addControl "profilePresets";
	
	editorTemplate -callCustom "AE_preset_ShellMod_create" "AE_preset_ShellMod_edit" "profilePresets";
	editorTemplate -callCustom "AE_presetList_ShellMod_create" "AE_presetList_ShellMod_edit" "";
	
	editorTemplate -endLayout;

	editorTemplate -beginLayout "UV options" -collapse 0;
	editorTemplate -addControl "uvOffsetU";
	editorTemplate -addControl "uvOffsetV";
	editorTemplate  -label "Auto U Offset" -addControl "uvOffsetUAutoOffset";
	editorTemplate  -label "Auto U Offset Padding" -addControl "uvOffsetUAutoOffsetPadding";
	
	editorTemplate -endLayout;
	
	editorTemplate -beginLayout "Global settings" -collapse 0;
	editorTemplate -callCustom "AE_del_ShellMod_create" "AE_del_ShellMod_edit" "";
	
	editorTemplate -endLayout;
	
	editorTemplate -beginLayout "Plug-in Info" -collapse 1;
	editorTemplate -callCustom "AE_website_create" "AE_website_edit" "";
	editorTemplate -endLayout;
	
	editorTemplate -suppress "inMesh";
	
	AEdependNodeTemplate $nodeName;
	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
	
	
}
global proc AE_preset_ShellMod_set(int $id, string $attr)
{
}

global proc AE_set_ProfileType(int $i_type, string $s_nodeName)
{
    setAttr ($s_nodeName + ".profilePresets " ) $i_type;
}

global proc AE_preset_ShellMod_create(string $attrName)
{
    string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    
	setUITemplate -pst attributeEditorPresetsTemplate;
    
    
    separator -height 10 -style "in";
    
    gridLayout -numberOfColumns 21 -cellWidthHeight 18 18 -bgc 0.2 0.2 0.2;
    iconTextButton -iol "cu" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(0," + "\"" + $nodeName[0] + "\"" + ")") "icon0";
    iconTextButton -iol "2" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(1," + "\"" + $nodeName[0] + "\"" + ")") "icon1";
    iconTextButton -iol "3" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(2," + "\"" + $nodeName[0] + "\"" + ")") "icon2";
    iconTextButton -iol "4" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(3," + "\"" + $nodeName[0] + "\"" + ")") "icon3";
    iconTextButton -iol "5" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(4," + "\"" + $nodeName[0] + "\"" + ")") "icon4";
    iconTextButton -iol "6" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(5," + "\"" + $nodeName[0] + "\"" + ")") "icon5";
    iconTextButton -iol "7" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(6," + "\"" + $nodeName[0] + "\"" + ")") "icon6";
    iconTextButton -iol "8" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(7," + "\"" + $nodeName[0] + "\"" + ")") "icon7";
    iconTextButton -iol "9" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(8," + "\"" + $nodeName[0] + "\"" + ")") "icon8";
    iconTextButton -iol "10" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(9," + "\"" + $nodeName[0] + "\"" + ")") "icon9";
    iconTextButton -iol "11" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(10," + "\"" + $nodeName[0] + "\"" + ")") "icon10";
    iconTextButton -iol "12" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(11," + "\"" + $nodeName[0] + "\"" + ")") "icon11";
    iconTextButton -iol "13" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(12," + "\"" + $nodeName[0] + "\"" + ")") "icon12";
    iconTextButton -iol "14" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(13," + "\"" + $nodeName[0] + "\"" + ")") "icon13";
    iconTextButton -iol "15" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(14," + "\"" + $nodeName[0] + "\"" + ")") "icon14";
    iconTextButton -iol "16" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(15," + "\"" + $nodeName[0] + "\"" + ")") "icon15";
    iconTextButton -iol "17" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(16," + "\"" + $nodeName[0] + "\"" + ")") "icon16";
    iconTextButton -iol "18" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(17," + "\"" + $nodeName[0] + "\"" + ")") "icon17";
    iconTextButton -iol "19" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(18," + "\"" + $nodeName[0] + "\"" + ")") "icon18";
    iconTextButton -iol "20" -image "shellModNode_Preset.png" -c ("AE_set_ProfileType(19," + "\"" + $nodeName[0] + "\"" + ")") "icon19";
	setParent ..;
	
	setUITemplate -ppt;
}

global proc AE_preset_ShellMod_edit(string $attrName)
{
    string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    
    iconTextButton -edit -c ("AE_set_ProfileType(0," + "\"" + $nodeName[0] + "\"" + ")") "icon0";
    iconTextButton -edit -c ("AE_set_ProfileType(1," + "\"" + $nodeName[0] + "\"" + ")") "icon1";
    iconTextButton -edit -c ("AE_set_ProfileType(2," + "\"" + $nodeName[0] + "\"" + ")") "icon2";
    iconTextButton -edit -c ("AE_set_ProfileType(3," + "\"" + $nodeName[0] + "\"" + ")") "icon3";
    iconTextButton -edit -c ("AE_set_ProfileType(4," + "\"" + $nodeName[0] + "\"" + ")") "icon4";
    iconTextButton -edit -c ("AE_set_ProfileType(5," + "\"" + $nodeName[0] + "\"" + ")") "icon5";
    iconTextButton -edit -c ("AE_set_ProfileType(6," + "\"" + $nodeName[0] + "\"" + ")") "icon6";
    iconTextButton -edit -c ("AE_set_ProfileType(7," + "\"" + $nodeName[0] + "\"" + ")") "icon7";
    iconTextButton -edit -c ("AE_set_ProfileType(8," + "\"" + $nodeName[0] + "\"" + ")") "icon8";
    iconTextButton -edit -c ("AE_set_ProfileType(9," + "\"" + $nodeName[0] + "\"" + ")") "icon9";
    iconTextButton -edit -c ("AE_set_ProfileType(10," + "\"" + $nodeName[0] + "\"" + ")") "icon10";
    iconTextButton -edit -c ("AE_set_ProfileType(11," + "\"" + $nodeName[0] + "\"" + ")") "icon11";
    iconTextButton -edit -c ("AE_set_ProfileType(12," + "\"" + $nodeName[0] + "\"" + ")") "icon12";
    iconTextButton -edit -c ("AE_set_ProfileType(13," + "\"" + $nodeName[0] + "\"" + ")") "icon13";
    iconTextButton -edit -c ("AE_set_ProfileType(14," + "\"" + $nodeName[0] + "\"" + ")") "icon14";
    iconTextButton -edit -c ("AE_set_ProfileType(15," + "\"" + $nodeName[0] + "\"" + ")") "icon15";
    iconTextButton -edit -c ("AE_set_ProfileType(16," + "\"" + $nodeName[0] + "\"" + ")") "icon16";
    iconTextButton -edit -c ("AE_set_ProfileType(17," + "\"" + $nodeName[0] + "\"" + ")") "icon17";
    iconTextButton -edit -c ("AE_set_ProfileType(18," + "\"" + $nodeName[0] + "\"" + ")") "icon18";
    iconTextButton -edit -c ("AE_set_ProfileType(19," + "\"" + $nodeName[0] + "\"" + ")") "icon19";
}

global proc AE_presetList_ShellMod_create(string $attrName)
{
    string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    
    // Crete preset list
    
    separator -height 10 -style "in";
	textScrollList -allowMultiSelection false -h 120 "sl_presets";
    setParent ..;
    // Populate preset list
    
    
    string $sm_pr_path = eval("getAttr " + $nodeName[0] + ".presetFolderPath");
    
    string $enumFields_list[] = `getFileList -fs "*.smp" -folder $sm_pr_path`;
    
    string $enumName[];
    
    
    for( $i=0; $i<size($enumFields_list); ++$i )
	{
	    tokenize($enumFields_list[$i], ".", $enumName);
	    textScrollList -edit -append $enumName[0] "sl_presets";
	}
    
    // Create add / remove preset icons
    separator -height 10 -style "in";
    
    rowLayout -numberOfColumns 5 -h 25 -adjustableColumn 4 -bgc 0.2 0.2 0.2;
    iconTextButton -w 20 -style "iconAndTextHorizontal" -image1 "shellModNode_Apply.png" -label "apply preset" -bgc 0.3 0.3 0.3 -c  ("AE_apply_customProfile_ShellMod " + $nodeName[0] ) "pres_appl";
	iconTextButton -w 50 -style "iconAndTextHorizontal" -image1 "shellModNode_Plus.png" -label "add" -bgc 0.4 0.4 0.4 -c  ("AE_add_customProfile_ShellMod " + $nodeName[0] ) "pres_add";
	iconTextButton  -w 90 -style "iconAndTextHorizontal" -image1 "shellModNode_Minus.png" -label "remove" -bgc 0.6 0.2 0.3 -c  ("AE_remove_customProfile_ShellMod " + $nodeName[0] ) "pres_rem";
	textField -pht "Untitled" "t_renamePreset";
	iconTextButton -w 80 -style "iconAndTextHorizontal" -image1 "shellModNode_Refresh.png" -label "refresh" -bgc 0.6 0.6 0.6 -c  ("AE_refresh_customProfile_ShellMod " + $nodeName[0] ) "pres_refresh";
	
	setParent ..;
	
	
    
}

global proc AE_presetList_ShellMod_edit(string $attrName)
{
    string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    
    iconTextButton -edit -c ("AE_apply_customProfile_ShellMod " + $nodeName[0] ) "pres_appl";
	iconTextButton -edit -c ("AE_add_customProfile_ShellMod " + $nodeName[0] ) "pres_add";
	iconTextButton -edit -c ("AE_remove_customProfile_ShellMod " + $nodeName[0] ) "pres_rem";
	iconTextButton -edit -c ("AE_refresh_customProfile_ShellMod " + $nodeName[0] ) "pres_refresh";
    
}


// --------------
// Custom profile
global proc AE_refresh_customProfile_ShellMod(string $nodeName)
{
    
    string $sm_pr_path = eval("getAttr " + $nodeName + ".presetFolderPath");
    string $enumFields_list[] = `getFileList -fs "*.smp" -folder $sm_pr_path`;
    
    string $enumName[];
    
    textScrollList -edit -ra "sl_presets";
    
    for( $i=0; $i<size($enumFields_list); ++$i )
	{
	    tokenize($enumFields_list[$i], ".", $enumName);
	    textScrollList -edit -append $enumName[0] "sl_presets";
	}
	
	float $pfR =  `getAttr ($nodeName+".profileRamp[0].profileRamp_Position")`;
	setAttr ($nodeName+".profileRamp[0].profileRamp_Position") $pfR;
}

global proc AE_apply_customProfile_ShellMod(string $attrName)
{
    string $nodeName[];
    tokenize($attrName, ".", $nodeName);
	
    string $presetName[];
    $presetName = `textScrollList -query -si "sl_presets"`;
    
    if ($presetName[0] != "") 
    {
        string $sm_pr_path = eval("getAttr " + $nodeName[0] + ".presetFolderPath");
        shellModCommand -lp $presetName -pp $sm_pr_path -sm $nodeName[0];
        textScrollList -edit -si $presetName "sl_presets";
    }
    
    setAttr ($nodeName[0] + ".profilePresets") 0;
    AE_refresh_customProfile_ShellMod($nodeName[0]);
    
    
}

global proc AE_add_customProfile_ShellMod(string $attrName)
{
    string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    string $newPresetName;
    $newPresetName = `textField -query -tx "t_renamePreset"`;
    
    //int $s_count = `size $newPresetName`;
    if ($newPresetName == "") { $newPresetName = "untitled";}
    
    string $sm_pr_path = eval("getAttr " + $nodeName[0] + ".presetFolderPath");
    string $enumFields_list[] = `getFileList -fs "*.smp" -folder $sm_pr_path`;
    string $enumName[];
    
    int $isSame = 0;
    
    for( $i=0; $i<size($enumFields_list); ++$i )
	{
	    tokenize($enumFields_list[$i], ".", $enumName);
	    
	    if($enumName[0] == $newPresetName)
	    {
	        string $conFirmVal = `confirmDialog -title ("Overwrite " + $newPresetName) -message "Are you sure?"
    -button "Yes" -button "No" -defaultButton "Yes"
    -cancelButton "No" -dismissString "No"`;
    
            if($conFirmVal == "Yes")
            {
                shellModCommand -sp $newPresetName -pp $sm_pr_path -sm $nodeName[0];
                $isSame = 1;
            }
            
            if($conFirmVal == "No")
            {
                $isSame = 1;
            }
	    }
	    
	}
    
    if( $isSame == 0)
    {
        shellModCommand -sp $newPresetName -pp $sm_pr_path -sm $nodeName[0];
    }
    
    AE_refresh_customProfile_ShellMod($nodeName[0]);
    
}

global proc AE_remove_customProfile_ShellMod(string $attrName)
{
    string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    
    string $presetName[];
    $presetName = `textScrollList -query -si "sl_presets"`;
    
    if ($presetName[0] != "") 
    {

        string $conFirmVal = `confirmDialog -title "Delete" -message "Are you sure?" -button "Yes" -button "No" -defaultButton "Yes" -cancelButton "No" -dismissString "No"`;
    
            if($conFirmVal == "Yes")
            {
                string $sm_pr_path = eval("getAttr " + $nodeName[0] + ".presetFolderPath");
                sysFile -delete ($sm_pr_path + $presetName[0] + ".smp");
                AE_refresh_customProfile_ShellMod($nodeName[0]);
            }
            
            if($conFirmVal == "No")
            {
                
            }

    }
    
    
}

// ----------------------------
// Global window Create / Edit
global proc AE_del_ShellMod_create(string $attrName)
{
	string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    iconTextButton -h 22 -style "iconAndTextHorizontal" -image1 "shellModNode_Trash.png" -label "Remove ShellMod from selected object"  -bgc 0.6 0.2 0.3 -c  ("AE_remove_ShellMod " + $nodeName[0] );
}

global proc AE_del_ShellMod_edit(string $attrName)
{
}

// ----------------------------
// Remove shellmod from object
global proc AE_remove_ShellMod(string $attrName)
{
shellModCommand -r;
}

global proc AE_launch_website()
{
    launch -web "http://gumroad.com/creativecase";
}

// ----------------------------
// Global window Create / Edit
global proc AE_website_create(string $attrName)
{
	string $nodeName[];
    tokenize($attrName, ".", $nodeName);
    
    string $sm_pr_path = eval("getAttr " + $nodeName[0] + ".presetFolderPath");
    
    rowLayout -numberOfColumns 3 -adjustableColumn 2 -bgc 0.2 0.2 0.2;
    text -al "left" -label "Preset path";
    textField -ed false -tx $sm_pr_path;
    iconTextButton -style "iconOnly" -image1 "shellModNode_CCLogo.png" -c "AE_launch_website()";

    setParent ..;
}

global proc AE_website_edit(string $attrName)
{
}